# frozen_string_literal: true

require_relative 'lib/nodes/value'
require_relative 'lib/nodes/boolean_value'
require_relative 'lib/nodes/string_value'
require_relative 'lib/nodes/integer_value'
require_relative 'lib/nodes/error'
require_relative 'lib/nodes/message'
require_relative 'lib/evaluator_error'
require_relative 'lib/evaluator'
require_relative 'lib/expressions/binary_operators'
require_relative 'lib/expressions/unary_operators'
require_relative 'lib/expressions/assign_variables'
require_relative 'lib/expressions/resolve_variables'
require_relative 'lib/expressions/runtime_value'
require_relative 'lib/expressions/functions'
require_relative 'lib/expressions/functions/args'
require_relative 'lib/expressions/functions/add_ints'
require_relative 'lib/expressions/functions/prod_ints'
require_relative 'lib/expressions/functions/factorial'
require_relative 'lib/expressions/commands'
require_relative 'lib/expressions/console_commands'
require_relative 'lib/expressions/console_commands/new_console_window'
